name: ProductBot - Test Post (Immediate)

on:
  workflow_dispatch:
    inputs:
      script_path:
        description: "Path to the Python script to run"
        required: true
        default: "bots/product_bot_v2.py"
        type: string
      openai_model:
        description: "OpenAI model (optional)"
        required: false
        default: "gpt-4o-mini"
        type: string
      dry_run:
        description: "If your script supports DRY_RUN, set true to avoid posting"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

permissions:
  contents: read

concurrency:
  group: productbot-test
  cancel-in-progress: false

jobs:
  test-post:
    name: Post Now
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install tweepy openai

      - name: Run ProductBot (LIVE)
        env:
          # --- Required Secrets ---
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

          # --- Optional knobs ---
          OPENAI_MODEL: ${{ github.event.inputs.openai_model }}
          AFFILIATE_TAG: futurebutnotn-20
          TRACKING_IDS_BY_MODE: '{"spiky":"futurebutnotn-20","confession":"futurebutnotn-21","problem_fix":"futurebutnotn-22","brand_tax":"futurebutnotn-23","micro_drill":"futurebutnotn-24","two_choice":"futurebutnotn-25"}'
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          set -euo pipefail
          python "${{ github.event.inputs.script_path }}"

      - name: Upload logs (tweet logs, metrics, bandit state)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: productbot-debug-${{ github.run_id }}
          path: |
            bots/logs/**
            bots/state/**
          if-no-files-found: ignore
