name: 🧪 Manual Test — TrendParasite

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Enable dry-run mode (skip Twitter post)?"
        required: true
        default: "true"

jobs:
  test-trendparasite:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: pip install -r trendparasite/requirements.txt

      - name: 🧪 Run TrendParasite (dry run)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "🧪 Running TrendParasite with test_mode=${{ github.event.inputs.test_mode }}"

          if [[ "${{ github.event.inputs.test_mode }}" == "true" ]]; then
            echo "⚠️ Disabling actual Twitter post..."
            sed -i 's/client.create_tweet/# client.create_tweet/' trendparasite/trend_sniffer.py
          fi

          python trendparasite/trend_sniffer.py
