name: TrendParasite Manual Test

on:
  workflow_dispatch:  # Trigger manually only

jobs:
  trendparasite:
    runs-on: ubuntu-latest
    name: 🧠 Run TrendParasite (Manual Test)

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}

      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: pip install -r trendparasite/requirements.txt

      - name: 🚀 Run TrendParasite
        run: python trendparasite/trend_sniffer.py
